name: "Helloworld workflow"

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "printing helloworld"
        run: echo "Hello world"

      - name: "printing java"
        run: echo "java"

      - name: "Printing current date"
        run: date

      - name: "Making folder"
        run: mkdir "Krish jain"

      - name: "Printing all folders if any"
        run: ls -la
