name: "Helloworld workflow"

on:
  push:
    branches: master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "printing helloworld"
        run: echo "Hello world"

      - name: "printing java"
        run: echo "java"
